site_name: Betswave Whitepaper
site_description: Betswave Whitepaper v1.1
# site_url: https://whitepaper.betswave.io/
repo_url: https://github.com/betswave/whitepaper
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.top
    - content.action.edit
    - toc.follow

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes

nav:
  - Home: index.md
  - Executive Summary: executive-summary.md
  - Introduction: introduction.md
  - Market Opportunity: market-opportunity.md
  - WAVE Token: wave-token.md
  - ORCA Utility: orca-utility.md
  - Legal/Disclaimer: legal-disclaimer.md
  - Roadmap: roadmap.md
  - Appendix: appendix.md
